import './globals.css'
import type { Metadata } from 'next'
import { Inter, Lexend } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
const lexend = Lexend({
  subsets: ['latin'],
  weight: '500',
});

export const metadata: Metadata = {
  title: 'Home - FreeLancer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
